name: Deploy

on:
  push:
    branches:
      - dev-heroku

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'pacific-fjord-65921' #Must be unique in Heroku
          heroku_email: 'ycsteven.tsao@gmail.com'
